In [1]:
%run "/Users/audreyburggraf/Desktop/QUEEN'S/THESIS RESEARCH/PLOTTING C29 989/constants.py"

/opt/anaconda3/lib/python3.9/site-packages/pandas/core/computation/expressions.py:21: UserWarning: Pandas requires version '2.8.4' or newer of 'numexpr' (version '2.7.3' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
/opt/anaconda3/lib/python3.9/site-packages/pandas/core/arrays/masked.py:61: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.2' currently installed).
  from pandas.core import (
/opt/anaconda3/lib/python3.9/site-packages/numpy/core/fromnumeric.py:3432: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/opt/anaconda3/lib/python3.9/site-packages/numpy/core/_methods.py:190: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)

In [2]:
%run "/Users/audreyburggraf/Desktop/QUEEN'S/THESIS RESEARCH/PLOTTING C29 989/FUNCTIONS/load_functions"

/opt/anaconda3/lib/python3.9/site-packages/dsharp_opac/dsharp_opac.py:47: UserWarning: could not import compiled mie code - mie calculation will be slow
  warnings.warn(

fortran mie routines unavailable

In [3]:
from mpl_toolkits.axes_grid1.inset_locator import inset_axes

# Load POLF

In [4]:
all_bands    = ["Band 4 nterms2",  "Band 5 robust -1",     "Band 6", "Band 7 nterms2"]

In [5]:
# df_POLF_old = load_POLF(all_bands, print_things = True, bias = 'old')

# df_POLF_old.round(2)

In [6]:
df_POLF_biased = load_POLF(all_bands, print_things = True, bias = 'biased')

df_POLF_biased.round(3)

Band = Band 4 nterms2
filename = constants_BAND4_nterms2_biased.csv
['POLF_Gaussian', 'POLF_err_Gaussian', 'POLF_maxPOLI', 'POLF_err_maxPOLI', 'POLF_maxStokesI', 'POLF_err_maxStokesI']
Band = Band 5 robust -1
filename = constants_BAND5_robust_minus1_biased.csv
['POLF_Gaussian', 'POLF_err_Gaussian', 'POLF_maxPOLI', 'POLF_err_maxPOLI', 'POLF_maxStokesI', 'POLF_err_maxStokesI']
Band = Band 6
filename = constants_BAND6_biased.csv
['POLF_Gaussian', 'POLF_err_Gaussian', 'POLF_maxPOLI', 'POLF_err_maxPOLI', 'POLF_maxStokesI', 'POLF_err_maxStokesI']
Band = Band 7 nterms2
filename = constants_BAND7_nterms2_biased.csv
['POLF_Gaussian', 'POLF_err_Gaussian', 'POLF_maxPOLI', 'POLF_err_maxPOLI', 'POLF_maxStokesI', 'POLF_err_maxStokesI']
 in load_POLF, results = {'Band': ['Band 4 nterms2', 'Band 5 robust -1', 'Band 6', 'Band 7 nterms2'], 'POLF_Gaussian': [1.1646626, 1.3506356000000002, 1.41269695, 0.898293], 'POLF_err_Gaussian': [0.04164333269914, 0.026957956839170003, 0.030886987, 0.0162191787361], 'POLF_maxPOLI': [1.561384, 1.5137895000000001, 1.4862873, 1.0841521], 'POLF_err_maxPOLI': [0.040507176933380004, 0.026619172979379997, 0.030210346000000003, 0.014223440147289998], 'POLF_maxStokesI': [1.3677061000000001, 1.4034492, 1.4639224, 1.0421403], 'POLF_err_maxStokesI': [0.03790606194433, 0.02613257528001, 0.029772913, 0.0141318535827]}

,Band,POLF_Gaussian,POLF_err_Gaussian,POLF_maxPOLI,POLF_err_maxPOLI,POLF_maxStokesI,POLF_err_maxStokesI,POLF_mean
0,Band 4 nterms2,1.165,0.042,1.561,0.041,1.368,0.038,0.702
1,Band 5 robust -1,1.351,0.027,1.514,0.027,1.403,0.026,0.725
2,Band 6,1.413,0.031,1.486,0.030,1.464,0.030,0.742
3,Band 7 nterms2,0.898,0.016,1.084,0.014,1.042,0.014,0.512

In [7]:
df_POLF_debiased = load_POLF(all_bands, print_things = True, bias = 'debiased')

df_POLF_debiased.round(3)

Band = Band 4 nterms2
filename = constants_BAND4_nterms2_debiased.csv
['POLF_Gaussian', 'POLF_err_Gaussian', 'POLF_maxPOLI', 'POLF_err_maxPOLI', 'POLF_maxStokesI', 'POLF_err_maxStokesI']
Band = Band 5 robust -1
filename = constants_BAND5_robust_minus1_debiased.csv
['POLF_Gaussian', 'POLF_err_Gaussian', 'POLF_maxPOLI', 'POLF_err_maxPOLI', 'POLF_maxStokesI', 'POLF_err_maxStokesI']
Band = Band 6
filename = constants_BAND6_debiased.csv
['POLF_Gaussian', 'POLF_err_Gaussian', 'POLF_maxPOLI', 'POLF_err_maxPOLI', 'POLF_maxStokesI', 'POLF_err_maxStokesI']
Band = Band 7 nterms2
filename = constants_BAND7_nterms2_debiased.csv
['POLF_Gaussian', 'POLF_err_Gaussian', 'POLF_maxPOLI', 'POLF_err_maxPOLI', 'POLF_maxStokesI', 'POLF_err_maxStokesI']
 in load_POLF, results = {'Band': ['Band 4 nterms2', 'Band 5 robust -1', 'Band 6', 'Band 7 nterms2'], 'POLF_Gaussian': [1.1638928, 1.3484494, 1.41269695, 0.8981155], 'POLF_err_Gaussian': [0.040598361141059996, 0.0765298153593, 0.030886987, 0.01717186472986], 'POLF_maxPOLI': [1.5608873, 1.5119315, 1.4862873, 1.0840478], 'POLF_err_maxPOLI': [0.039390835391389996, 0.07498792265646001, 0.030210346000000003, 0.01504517435846], 'POLF_maxStokesI': [1.3672079, 1.4014986999999999, 1.4639224, 1.0420333], 'POLF_err_maxStokesI': [0.03691720986757, 0.07397171203147, 0.029772913, 0.01493462948155]}

,Band,POLF_Gaussian,POLF_err_Gaussian,POLF_maxPOLI,POLF_err_maxPOLI,POLF_maxStokesI,POLF_err_maxStokesI,POLF_mean
0,Band 4 nterms2,1.164,0.041,1.561,0.039,1.367,0.037,0.701
1,Band 5 robust -1,1.348,0.077,1.512,0.075,1.401,0.074,0.748
2,Band 6,1.413,0.031,1.486,0.030,1.464,0.030,0.742
3,Band 7 nterms2,0.898,0.017,1.084,0.015,1.042,0.015,0.512

In [8]:
# raise SystemExit("Stop here")

# Load in data

In [9]:
%run "/Users/audreyburggraf/Desktop/QUEEN'S/THESIS RESEARCH/PLOTTING C29 989/FITS FILES/BAND4_nterms2/load_band4_data_nterms2.py"

path = band4_nterms2_data_folder_path

B4 = BuildBandDictionary(
    path,
    StokesI_wcs,
    xmin,
    xmax,
    ymin,
    ymax,
    reference_length_pix,
    reference_length_AU,
    BMAJ_pix,
    BMIN_pix,
    BPA_deg_cartesian,
    max_length_pix,
    reference_fraction,
    POLI_debiased_mJy,
    StokesI_mJy, StokesI_stretched_mJy_grid, StokesI_unstretched_cbar_ticks_grid,
    RA_centre_pix, Dec_centre_pix,
    POLF_debiased
)

band = Band 4 nterms2
max_str = 'J163135.750-240128.700'
StokesI_wcs CRPIX = [513. 513.]
StokesI_wcs CDELT = [-5.e-06  5.e-06]
Pixel scale = 0.018 arcsec/pixel
Dec_max_pix = 581

Biased

In [10]:
# %run "/Users/audreyburggraf/Desktop/QUEEN'S/THESIS RESEARCH/PLOTTING C29 989/FITS FILES/BAND5/load_band5_data.py"

# path = band5_data_folder_path

# B5 = BuildBandDictionary(
#     path,
#     StokesI_wcs,
#     xmin,
#     xmax,
#     ymin,
#     ymax,
#     reference_length_pix,
#     reference_length_AU,
#     BMAJ_pix,
#     BMIN_pix,
#     BPA_deg_cartesian,
#     max_length_pix,
#     reference_fraction,
#     POLI_debiased_mJy, # There is no Band 5 debiased yet,
#     StokesI_mJy
# )

# stream_vectors_B5 = stream_vectors

In [11]:
%run "/Users/audreyburggraf/Desktop/QUEEN'S/THESIS RESEARCH/PLOTTING C29 989/FITS FILES/BAND5_robust_minus1/load_band5_robust_minus1_data.py"
path = band5_robust_minus1_data_folder_path

B5_R1 = BuildBandDictionary(
    path,
    StokesI_wcs,
    xmin,
    xmax,
    ymin,
    ymax,
    reference_length_pix,
    reference_length_AU,
    BMAJ_pix,
    BMIN_pix,
    BPA_deg_cartesian,
    max_length_pix,
    reference_fraction,
    POLI_debiased_mJy, 
    StokesI_mJy, StokesI_stretched_mJy_grid, StokesI_unstretched_cbar_ticks_grid,
    RA_centre_pix, Dec_centre_pix,
    POLF_debiased
)

stream_vectors_B5_R1 = stream_vectors

band = Band 5 robust -1
max_str = 'J163135.750-240128.700'
StokesI_wcs CRPIX = [513. 513.]
StokesI_wcs CDELT = [-5.e-06  5.e-06]
Pixel scale = 0.018 arcsec/pixel
Dec_max_pix = 581

No streamer
Streamer

In [12]:
%run "/Users/audreyburggraf/Desktop/QUEEN'S/THESIS RESEARCH/PLOTTING C29 989/FITS FILES/BAND6/load_band6_data.py"


path = band6_data_folder_path

B6 = BuildBandDictionary(
    path,
    StokesI_wcs,
    xmin,
    xmax,
    ymin,
    ymax,
    reference_length_pix,
    reference_length_AU,
    BMAJ_pix,
    BMIN_pix,
    BPA_deg_cartesian,
    max_length_pix,
    reference_fraction,
    POLI_mJy,
    StokesI_mJy, StokesI_stretched_mJy_grid, StokesI_unstretched_cbar_ticks_grid,
    RA_centre_pix, Dec_centre_pix,
    POLF
)

band = Band 6
max_str = 'J163135.750-240128.700'
StokesI_wcs CRPIX = [864. 864.]
StokesI_wcs CDELT = [-5.e-06  5.e-06]
Pixel scale = 0.018 arcsec/pixel
Dec_max_pix = 895

In load_band6_data.py, ymax = 895

In [13]:
%run "/Users/audreyburggraf/Desktop/QUEEN'S/THESIS RESEARCH/PLOTTING C29 989/FITS FILES/BAND7_nterms2/load_band7_nterms2_data.py"

path = band7_nterms2_data_folder_path

B7 = BuildBandDictionary(
    path,
    StokesI_wcs,
    xmin,
    xmax,
    ymin,
    ymax,
    reference_length_pix,
    reference_length_AU,
    BMAJ_pix,
    BMIN_pix,
    BPA_deg_cartesian,
    max_length_pix,
    reference_fraction,
    POLI_debiased_mJy,
    StokesI_mJy, StokesI_stretched_mJy_grid, StokesI_unstretched_cbar_ticks_grid,
    RA_centre_pix, Dec_centre_pix,
    POLF_debiased
    
)

band = Band 7 nterms2
max_str = 'J163135.750-240128.700'
StokesI_wcs CRPIX = [513. 513.]
StokesI_wcs CDELT = [-5.e-06  5.e-06]
Pixel scale = 0.018 arcsec/pixel
Dec_max_pix = 581

# Median POLF values

In [14]:
df_POLF_debiased.round(2)

,Band,POLF_Gaussian,POLF_err_Gaussian,POLF_maxPOLI,POLF_err_maxPOLI,POLF_maxStokesI,POLF_err_maxStokesI,POLF_mean
0,Band 4 nterms2,1.16,0.04,1.56,0.04,1.37,0.04,0.70
1,Band 5 robust -1,1.35,0.08,1.51,0.07,1.40,0.07,0.75
2,Band 6,1.41,0.03,1.49,0.03,1.46,0.03,0.74
3,Band 7 nterms2,0.90,0.02,1.08,0.02,1.04,0.01,0.51

In [20]:
for i, b in enumerate([B4, B5_R1, B6, B7]):

    # Maximum Stokes I and its location
    max_StokesI = np.nanmax(b['StokesI_mJy'])
    max_idx = np.unravel_index(
        np.nanargmax(b['StokesI_mJy']),
        b['StokesI_mJy'].shape
    )

    # Coordinates of maximum Stokes I
    y, x = max_idx

    # Values at that location
    POLI_debiased = b['POLI_debiased_mJy'][y, x]
    POLI_StokesI = POLI_debiased / max_StokesI
    POLF_debiased = b['POLF_debiased'][y, x]

    print(rf'For Band {i + 4}:')
    print(rf'    Maximum Stokes I = {max_StokesI:.2f} mJy')
    print(rf'    Pixel coordinates = (x, y) = ({x}, {y})')
    print(rf'    debiased POLI = {POLI_debiased:.2f} mJy')
    print(rf'    debiased POLI/Stokes I = {POLI_StokesI:.4f}')
    print(rf'    debiased POLF = {POLF_debiased:.4f}')
    print()

For Band 4:
    Maximum Stokes I = 26.14 mJy
    Pixel coordinates = (x, y) = (515, 509)
    debiased POLI = 0.36 mJy
    debiased POLI/Stokes I = 0.0137
    debiased POLF = 0.0137

For Band 5:
    Maximum Stokes I = 54.76 mJy
    Pixel coordinates = (x, y) = (515, 504)
    debiased POLI = 0.77 mJy
    debiased POLI/Stokes I = 0.0140
    debiased POLF = 0.0140

For Band 6:
    Maximum Stokes I = 90.76 mJy
    Pixel coordinates = (x, y) = (858, 827)
    debiased POLI = 1.33 mJy
    debiased POLI/Stokes I = 0.0146
    debiased POLF = 0.0146

For Band 7:
    Maximum Stokes I = 175.78 mJy
    Pixel coordinates = (x, y) = (515, 504)
    debiased POLI = 1.83 mJy
    debiased POLI/Stokes I = 0.0104
    debiased POLF = 0.0104

In [16]:
raise SystemExit("Stop here")

SystemExit: Stop here

/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py:3452: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)

# $\Delta \alpha$ and $\Delta \delta$ plots

In [ ]:
bands = [B4, B5_R1, B6, B7]
bands_idx = [4, 5, 6, 7]
centre_strings = [constants.centre_str_band4_nterms2,
                  constants.centre_str_band5_robust_minus1,
                  constants.centre_str_band6,
                  constants.centre_str_band7_nterms2]

fig, ax = MakeAllBandGridDelta(bands, centre_strings, 'Stokes I')


plt.savefig(image_folder_path + '/WRITEUP/StokesI_POLI/' + "StokesI_grid_robust_minus1_Delta_unstretched.pdf", 
            dpi=500, 
            bbox_inches='tight',
               facecolor='white')

In [ ]:
print(B7['StokesI_stretched_mJy_grid'].dtype)
print(B7['StokesI_stretched_mJy_grid'].shape)

In [ ]:
B5['Stokes Q']

In [ ]:
calculate_polarized_intensity_err(Q, U, 41, 41)

In [ ]:
calculate_polarized_intensity_err(Q, U, 13, 15)

In [ ]:
bands = [B4, B5_R1, B6, B7]
bands_idx = [4, 5, 6, 7]
centre_strings = [constants.centre_str_band4_nterms2,
                  constants.centre_str_band5_robust_minus1,
                  constants.centre_str_band6,
                  constants.centre_str_band7_nterms2]

fig, ax = MakeAllBandGridDelta(bands, centre_strings, 'Stokes I stretched')


plt.savefig(image_folder_path + '/WRITEUP/StokesI_POLI/' + "StokesI_grid_robust_minus1_Delta_stretched.pdf", 
            dpi=500, 
            bbox_inches='tight',
               facecolor='white')

In [ ]:
fig, ax = MakeAllBandGridDelta(bands, centre_strings, 'POLI', show_vectors = False)


for i, b in enumerate(bands):
    ax[i].plot(b['minor_x'],
        b['minor_y'],
        label = 'Minor Axis Slice',
        color = 'grey',
        lw = 3, 
        ls = "--")
    
plt.savefig(image_folder_path + "WRITEUP/Slices/" + "MinorAxisSliceGrid_robust_minus1_Delta.pdf",
            dpi=500, 
            bbox_inches='tight',
               facecolor='white')

In [ ]:
fig, ax = MakeAllBandGridDelta(bands, centre_strings, 'POLI')



plt.savefig(image_folder_path + '/WRITEUP/StokesI_POLI/' + "POLI_grid_robust_minus1_Delta.pdf", 
            dpi=500, 
            bbox_inches='tight',
               facecolor='white')

# Older Plots

In [ ]:
# bands = [B4, B5_R1, B6, B7]
# bands_idx = [4, 5, 6, 7]

# stream_vectors = stream_vectors_B5_R1

# vector_lw = 2
# AU100_lw = 2
# AU100_fs = 15
# label = 'wavelength'
# x_pos = 0.06
# y_pos = 0.85
# beam_lw = 1.5
# cbar_label_fs = 20

    
# text_fs = 20
# spine_width = 1

# fig, ax = MakeAllBandGridDelta(bands,
#            fig_x_size = 20, 
#                     fig_y_size = 6.5,
#                     label = 'wavelength',
#                     cmap = soft_colormap_v2,
#                    vector_lw = 2.2,
#                    axis_num_fs = 16,
#                 axis_label_fs = 22, 
#                    scalebar_fs = 16,
#                    beam_lw = 1.5,
#                    cbar_label_fs = 20,
#                     # This is for the 100 AU and label text
#                     x_pos = 0.06, 
#                     y_pos = 0.85,
#                     AU100_lw = 2.5,
#                     AU100_fs = 20, 
#                     text_fs = 20, 
#                     wspace = 0.12,
#                    for_poster = False,
#                     for_writeup = False, 
#                    ps = 1,
#                    cbar_shrink = 1)


    
# # plt.savefig(image_folder_path + '/WRITEUP/StokesI_POLI/' + "StokesI_grid.pdf", 
# #             dpi=500, 
# #             bbox_inches='tight',
# #                facecolor='white')

In [ ]:
# raise SystemExit("Stop here")

# Make the plot

In [ ]:
# # ---------------------------------------------------
# wantx = 48.45
# wanty = 14.7
# # ---------------------------------------------------
# figx = wantx * 20/54.19
# figy = wanty * 6/16.09
# # ---------------------------------------------------
# ps = 0.75


# vector_lw = 2.2

# fig, axes = MakeAllBandGrid(B4, B5, B6, B7, vector_lw = 2.8, 
# #                             AU100_fs = 20,
#                            axis_num_fs = poster_axis_num_fs * ps, 
#                             axis_label_fs = poster_axis_label_fs * ps, 
#                             AU100_lw = 3, 
#                             wspace = 0.12,
#                            for_poster = True,
#                            fig_x_size = figx, 
#                             fig_y_size = figy,
#                            ps = ps,
#                            cbar_shrink = 1)


# # fig.subplots_adjust(wspace=0.08, bottom=0.18, top=0.95, left=0.06, right=0.98)

# # Add streamer vectors to band 5 plot
# for row in stream_vectors:
#     axes[1].plot([row[0], row[1]], [row[2], row[3]], color='red', lw = vector_lw)

# fig.subplots_adjust(
#     left=0.155,
#     right=0.99,
#     bottom=0.14,
#     top=0.85,
#     wspace=0.10
# )
    
    
# plt.savefig(image_folder_path + '/POSTER/' + "POLI_grid.png", 
#             dpi=500, 
#             #bbox_inches='tight',
#                facecolor='white')

In [ ]:
# bands = [B4, B5, B6, B7]
# bands_idx = [4, 5, 6, 7]

# stream_vectors = stream_vectors_B5


# vector_lw = 2
# AU100_lw = 2
# AU100_fs = 15
# label = 'wavelength'
# x_pos = 0.06
# y_pos = 0.85
# beam_lw = 1.5
# cbar_label_fs = 20

    
# text_fs = 20
# spine_width = 1





# # These things should be the same for all bands
# StokesI_wcs = B4['StokesI_wcs']


# # Make the figure
# fig = plt.figure(figsize=(12, 5))
# axes = []

# for i, b in enumerate(bands):

#     ax = fig.add_subplot(1, 4, i + 1, projection=b['StokesI_wcs'])
#     axes.append(ax)


#     #ax.coords.frame.set_linewidth(spine_width)


#     # Plot POLI
#     im = ax.imshow(b['StokesI_mJy'], cmap = soft_colormap_v2)

#     # Add a cbar

#     # Make colorbar axis above plot
#     cax = inset_axes(
#         ax,
#         width="100%",
#         height="6%",
#         loc="upper center",
#         bbox_to_anchor=(0, 0.075, 1, 1),
#         bbox_transform=ax.transAxes,
#         borderpad=0
#     )

#     # Add colorbar
#     cbar1 = plt.colorbar(im, cax=cax, orientation="horizontal")

#     # Put ticks on top
#     cbar1.ax.xaxis.set_ticks_position("top")

#     # Format colorbar
#     cbar1.ax.tick_params(
#         labelsize=axis_num_fs,
#         which="major",
#         length=4,
#         direction="in",
#         width=spine_width
#     )

#     cbar1.outline.set_linewidth(spine_width)


#     # Add the vectors
#     for row in b['VectorsActual']:
#         ax.plot([row[0], row[1]], [row[2], row[3]], color='black', lw = vector_lw)

#     xmin = b['xmin']
#     xmax = b['xmax']
#     ymin = b['ymin']
#     ymax = b['ymax']



#     # Beam location
#     beam_x_pos = xmin - 0.1 * (xmin - xmax)
#     beam_y_pos = ymin - 0.1 * (ymin - ymax)


#     # Add y-axis label to the left
#     if i == 0:
#         ax.set_ylabel("Declination (ICRS)", fontsize=axis_label_fs)

#     # Add an x-axis label to all plots
#     ax.set_xlabel(" ")

#     # Set the x and y lims
#     ax.set_xlim(xmin, xmax)
#     ax.set_ylim(ymin, ymax)

#     # Add the line to each plot
#     # ---------------------------------------------------------
#     # Scalebar line
#     line_x_pos = xmax - 0.04 * (xmax - xmin)
#     line_y_pos = ymin - 0.14 * (ymin - ymax)  -10

#     x0 = line_x_pos - b['reference_length_pix']
#     x1 = line_x_pos

#     ax.plot(
#         [x0, x1],
#         [line_y_pos, line_y_pos],
#         color='black',
#         linewidth=AU100_lw
#     )

#     # ---------------------------------------------------------
#     # Convert midpoint from data coords -> axes coords
#     x_mid_data = (x0 + x1) / 2
#     y_mid_data = line_y_pos

#     display_coords = ax.transData.transform((x_mid_data, y_mid_data))
#     axes_coords = ax.transAxes.inverted().transform(display_coords)

#     x_axes, y_axes = axes_coords

#     # Text directly above middle of line
#     ax.text(
#         x_axes,
#         y_axes + 0.015,
#         f"{b['reference_length_AU']} AU",
#         transform=ax.transAxes,
#         fontsize=AU100_fs,
#         ha='center',
#         va='bottom'
#     )

#     add_band_label(ax, bands_idx[i], label, constants, x_pos = x_pos, y_pos = y_pos, 
#                    label_fs = text_fs, va = 'bottom')
#     # ---------------------------------------------------------


#     # Add the beam
#     beam = Ellipse((beam_x_pos, beam_y_pos), width=b['BMAJ_pix'], height=b['BMIN_pix'],  
#                angle=b['BPA_deg_cartesian'], edgecolor='black', facecolor='none', alpha=1, lw=beam_lw)

#     ax.add_patch(beam)

#     # Axis ticks and labels 
#     # ---------------------------------------------------------
#     # Only show y-axis numbers on far left plot
#     if i != 0:
#         ax.coords[1].set_ticklabel_visible(False)
#         ax.coords[1].set_axislabel('')
# #     # ---------------------------------------------------------
# #     # Tick locations and style
#     ax.coords[0].set_ticks(number=3, direction='in', width=spine_width)
#     ax.coords[1].set_ticks(number=5, direction='in', width=spine_width)

#     # Tick label sizes
#     ax.coords[0].set_ticklabel(size=axis_num_fs)
#     ax.coords[1].set_ticklabel(size=axis_num_fs)
# # #         # --------------------------------------------------------
#     # --------------------------------------------------------
# #     ax.coords[1].set_ticklabel_visible(True)
# #     ax.coords[0].set_ticklabel_visible(True)
#     # --------------------------------------------------------

# # Add streamer vectors to band 5 plot
# for row in stream_vectors:
#     axes[1].plot([row[0], row[1]], [row[2], row[3]], color='red', lw = vector_lw)


# fig.text(
#     0.5,
#     0.03,
#     "Right Ascension (ICRS)",
#     ha='center',
#     fontsize=axis_label_fs
# )



# fig.subplots_adjust(
#     left=0.05,
#     right=0.98,
#     bottom=0.12,
#     top=0.88,
#     wspace=0.12
# )


# fig.text(
#     0.5,          # centered
#     0.995,         # adjust as needed
#     r'Polarized Intensity [mJy beam$^{-1}$]',
#     ha='center',
#     va='top',
#     fontsize=cbar_label_fs
# )
    
    
# plt.savefig(image_folder_path + '/WRITEUP/StokesI_POLI/' + "StokesI_grid.pdf", 
#             dpi=500, 
#             bbox_inches='tight',
#                facecolor='white')

In [ ]:
# bands = [B4, B5_R1, B6, B7]
# bands_idx = [4, 51, 6, 7]

# stream_vectors = stream_vectors_B5_R1


# vector_lw = 2
# AU100_lw = 2
# AU100_fs = 15
# label = 'wavelength'
# x_pos = 0.06
# y_pos = 0.85
# beam_lw = 1.5
# cbar_label_fs = 20

    
# text_fs = 20
# spine_width = 1





# # These things should be the same for all bands
# StokesI_wcs = B4['StokesI_wcs']


# # Make the figure
# fig = plt.figure(figsize=(12, 5))
# axes = []

# for i, b in enumerate(bands):

#     ax = fig.add_subplot(1, 4, i + 1, projection=b['StokesI_wcs'])
#     axes.append(ax)


#     #ax.coords.frame.set_linewidth(spine_width)


#     # Plot POLI
#     im = ax.imshow(b['StokesI_mJy'], cmap = soft_colormap_v2)

#     # Add a cbar

#     # Make colorbar axis above plot
#     cax = inset_axes(
#         ax,
#         width="100%",
#         height="6%",
#         loc="upper center",
#         bbox_to_anchor=(0, 0.075, 1, 1),
#         bbox_transform=ax.transAxes,
#         borderpad=0
#     )

#     # Add colorbar
#     cbar1 = plt.colorbar(im, cax=cax, orientation="horizontal")

#     # Put ticks on top
#     cbar1.ax.xaxis.set_ticks_position("top")

#     # Format colorbar
#     cbar1.ax.tick_params(
#         labelsize=axis_num_fs,
#         which="major",
#         length=4,
#         direction="in",
#         width=spine_width
#     )

#     cbar1.outline.set_linewidth(spine_width)


#     # Add the vectors
#     for row in b['VectorsActual']:
#         ax.plot([row[0], row[1]], [row[2], row[3]], color='black', lw = vector_lw)

#     xmin = b['xmin']
#     xmax = b['xmax']
#     ymin = b['ymin']
#     ymax = b['ymax']



#     # Beam location
#     beam_x_pos = xmin - 0.1 * (xmin - xmax)
#     beam_y_pos = ymin - 0.1 * (ymin - ymax)


#     # Add y-axis label to the left
#     if i == 0:
#         ax.set_ylabel("Declination (ICRS)", fontsize=axis_label_fs)

#     # Add an x-axis label to all plots
#     ax.set_xlabel(" ")

#     # Set the x and y lims
#     ax.set_xlim(xmin, xmax)
#     ax.set_ylim(ymin, ymax)

#     # Add the line to each plot
#     # ---------------------------------------------------------
#     # Scalebar line
#     line_x_pos = xmax - 0.04 * (xmax - xmin)
#     line_y_pos = ymin - 0.14 * (ymin - ymax)  -10

#     x0 = line_x_pos - b['reference_length_pix']
#     x1 = line_x_pos

#     ax.plot(
#         [x0, x1],
#         [line_y_pos, line_y_pos],
#         color='black',
#         linewidth=AU100_lw
#     )

#     # ---------------------------------------------------------
#     # Convert midpoint from data coords -> axes coords
#     x_mid_data = (x0 + x1) / 2
#     y_mid_data = line_y_pos

#     display_coords = ax.transData.transform((x_mid_data, y_mid_data))
#     axes_coords = ax.transAxes.inverted().transform(display_coords)

#     x_axes, y_axes = axes_coords

#     # Text directly above middle of line
#     ax.text(
#         x_axes,
#         y_axes + 0.015,
#         f"{b['reference_length_AU']} AU",
#         transform=ax.transAxes,
#         fontsize=AU100_fs,
#         ha='center',
#         va='bottom'
#     )

#     add_band_label(ax, bands_idx[i], label, constants, x_pos = x_pos, y_pos = y_pos, 
#                    label_fs = text_fs, va = 'bottom')
#     # ---------------------------------------------------------


#     # Add the beam
#     beam = Ellipse((beam_x_pos, beam_y_pos), width=b['BMAJ_pix'], height=b['BMIN_pix'],  
#                angle=b['BPA_deg_cartesian'], edgecolor='black', facecolor='none', alpha=1, lw=beam_lw)

#     ax.add_patch(beam)

#     # Axis ticks and labels 
#     # ---------------------------------------------------------
#     # Only show y-axis numbers on far left plot
#     if i != 0:
#         ax.coords[1].set_ticklabel_visible(False)
#         ax.coords[1].set_axislabel('')
# #     # ---------------------------------------------------------
# #     # Tick locations and style
#     ax.coords[0].set_ticks(number=3, direction='in', width=spine_width)
#     ax.coords[1].set_ticks(number=5, direction='in', width=spine_width)

#     # Tick label sizes
#     ax.coords[0].set_ticklabel(size=axis_num_fs)
#     ax.coords[1].set_ticklabel(size=axis_num_fs)
# # #         # --------------------------------------------------------
#     # --------------------------------------------------------
# #     ax.coords[1].set_ticklabel_visible(True)
# #     ax.coords[0].set_ticklabel_visible(True)
#     # --------------------------------------------------------

# # Add streamer vectors to band 5 plot
# # for row in stream_vectors:
# #     axes[1].plot([row[0], row[1]], [row[2], row[3]], color='red', lw = vector_lw)


# fig.text(
#     0.5,
#     0.03,
#     "Right Ascension (ICRS)",
#     ha='center',
#     fontsize=axis_label_fs
# )



# fig.subplots_adjust(
#     left=0.05,
#     right=0.98,
#     bottom=0.12,
#     top=0.88,
#     wspace=0.12
# )


# fig.text(
#     0.5,          # centered
#     0.995,         # adjust as needed
#     r'Stokes I [mJy beam$^{-1}$]',
#     ha='center',
#     va='top',
#     fontsize=cbar_label_fs
# )
    
    
# plt.savefig(image_folder_path + '/WRITEUP/StokesI_POLI/' + "StokesI_grid_robust_minus1.pdf", 
#             dpi=500, 
#             bbox_inches='tight',
#                facecolor='white')

In [ ]:
# bands = [B4, B5, B6, B7]
# bands_idx = [4, 5, 6, 7]

# stream_vectors = stream_vectors_B5

# vector_lw = 2
# AU100_lw = 2
# AU100_fs = 15
# label = 'wavelength'
# x_pos = 0.06
# y_pos = 0.85
# beam_lw = 1.5
# cbar_label_fs = 20

    
# text_fs = 20
# spine_width = 1




# # These things should be the same for all bands
# StokesI_wcs = B4['StokesI_wcs']


# # Make the figure
# fig = plt.figure(figsize=(12, 5))
# axes = []

# for i, b in enumerate(bands):

#     ax = fig.add_subplot(1, 4, i + 1, projection=b['StokesI_wcs'])
#     axes.append(ax)


#     #ax.coords.frame.set_linewidth(spine_width)


#     # Plot POLI
#     im = ax.imshow(b['POLI_debiased_mJy'], cmap = soft_colormap_v2)

#     # Add a cbar

#     # Make colorbar axis above plot
#     cax = inset_axes(
#         ax,
#         width="100%",
#         height="6%",
#         loc="upper center",
#         bbox_to_anchor=(0, 0.075, 1, 1),
#         bbox_transform=ax.transAxes,
#         borderpad=0
#     )

#     # Add colorbar
#     cbar1 = plt.colorbar(im, cax=cax, orientation="horizontal")

#     # Put ticks on top
#     cbar1.ax.xaxis.set_ticks_position("top")

#     # Format colorbar
#     cbar1.ax.tick_params(
#         labelsize=axis_num_fs,
#         which="major",
#         length=4,
#         direction="in",
#         width=spine_width
#     )

#     cbar1.outline.set_linewidth(spine_width)


#     # Add the vectors
#     for row in b['VectorsActual']:
#         ax.plot([row[0], row[1]], [row[2], row[3]], color='black', lw = vector_lw)

#     xmin = b['xmin']
#     xmax = b['xmax']
#     ymin = b['ymin']
#     ymax = b['ymax']



#     # Beam location
#     beam_x_pos = xmin - 0.1 * (xmin - xmax)
#     beam_y_pos = ymin - 0.1 * (ymin - ymax)


#     # Add y-axis label to the left
#     if i == 0:
#         ax.set_ylabel("Declination (ICRS)", fontsize=axis_label_fs)

#     # Add an x-axis label to all plots
#     ax.set_xlabel(" ")

#     # Set the x and y lims
#     ax.set_xlim(xmin, xmax)
#     ax.set_ylim(ymin, ymax)

#     # Add the line to each plot
#     # ---------------------------------------------------------
#     # Scalebar line
#     line_x_pos = xmax - 0.04 * (xmax - xmin)
#     line_y_pos = ymin - 0.14 * (ymin - ymax)  -10

#     x0 = line_x_pos - b['reference_length_pix']
#     x1 = line_x_pos

#     ax.plot(
#         [x0, x1],
#         [line_y_pos, line_y_pos],
#         color='black',
#         linewidth=AU100_lw
#     )

#     # ---------------------------------------------------------
#     # Convert midpoint from data coords -> axes coords
#     x_mid_data = (x0 + x1) / 2
#     y_mid_data = line_y_pos

#     display_coords = ax.transData.transform((x_mid_data, y_mid_data))
#     axes_coords = ax.transAxes.inverted().transform(display_coords)

#     x_axes, y_axes = axes_coords

#     # Text directly above middle of line
#     ax.text(
#         x_axes,
#         y_axes + 0.015,
#         f"{b['reference_length_AU']} AU",
#         transform=ax.transAxes,
#         fontsize=AU100_fs,
#         ha='center',
#         va='bottom'
#     )

#     add_band_label(ax, bands_idx[i], label, constants, x_pos = x_pos, y_pos = y_pos, 
#                    label_fs = text_fs, va = 'bottom')
#     # ---------------------------------------------------------


#     # Add the beam
#     beam = Ellipse((beam_x_pos, beam_y_pos), width=b['BMAJ_pix'], height=b['BMIN_pix'],  
#                angle=b['BPA_deg_cartesian'], edgecolor='black', facecolor='none', alpha=1, lw=beam_lw)

#     ax.add_patch(beam)

#     # Axis ticks and labels 
#     # ---------------------------------------------------------
#     # Only show y-axis numbers on far left plot
#     if i != 0:
#         ax.coords[1].set_ticklabel_visible(False)
#         ax.coords[1].set_axislabel('')
# #     # ---------------------------------------------------------
# #     # Tick locations and style
#     ax.coords[0].set_ticks(number=3, direction='in', width=spine_width)
#     ax.coords[1].set_ticks(number=5, direction='in', width=spine_width)

#     # Tick label sizes
#     ax.coords[0].set_ticklabel(size=axis_num_fs)
#     ax.coords[1].set_ticklabel(size=axis_num_fs)
# # #         # --------------------------------------------------------
#     # --------------------------------------------------------
# #     ax.coords[1].set_ticklabel_visible(True)
# #     ax.coords[0].set_ticklabel_visible(True)
#     # --------------------------------------------------------

# # Add streamer vectors to band 5 plot
# for row in stream_vectors:
#     axes[1].plot([row[0], row[1]], [row[2], row[3]], color='red', lw = vector_lw)


# fig.text(
#     0.5,
#     0.03,
#     "Right Ascension (ICRS)",
#     ha='center',
#     fontsize=axis_label_fs
# )



# fig.subplots_adjust(
#     left=0.05,
#     right=0.98,
#     bottom=0.12,
#     top=0.88,
#     wspace=0.12
# )


# fig.text(
#     0.5,          # centered
#     0.995,         # adjust as needed
#     r'Polarized Intensity [mJy beam$^{-1}$]',
#     ha='center',
#     va='top',
#     fontsize=cbar_label_fs
# )
    
    
# plt.savefig(image_folder_path + '/WRITEUP/StokesI_POLI/' + "POLI_grid.pdf", 
#             dpi=500, 
#             bbox_inches='tight',
#                facecolor='white')

# # plt.savefig(image_folder_path + '/SLIDESHOW/POLI/' + "POLI_grid.jpeg", 
# #             dpi=500, 
# #             bbox_inches='tight',
# #                facecolor='white')

In [ ]:
# #

# bands = [B4, B5_R1, B6, B7]
# bands_idx = [4, 5, 6, 7]

# stream_vectors = stream_vectors_B5_R1

# vector_lw = 2
# AU100_lw = 2
# AU100_fs = 15
# label = 'wavelength'
# x_pos = 0.06
# y_pos = 0.85
# beam_lw = 1.5
# cbar_label_fs = 20

    
# text_fs = 20
# spine_width = 1




# # These things should be the same for all bands
# StokesI_wcs = B4['StokesI_wcs']


# # Make the figure
# fig = plt.figure(figsize=(12, 5))
# axes = []

# for i, b in enumerate(bands):

#     ax = fig.add_subplot(1, 4, i + 1, projection=b['StokesI_wcs'])
#     axes.append(ax)


#     #ax.coords.frame.set_linewidth(spine_width)


#     # Plot POLI
#     im = ax.imshow(b['POLI_debiased_mJy'], cmap = soft_colormap_v2)

#     # Add a cbar

#     # Make colorbar axis above plot
#     cax = inset_axes(
#         ax,
#         width="100%",
#         height="6%",
#         loc="upper center",
#         bbox_to_anchor=(0, 0.075, 1, 1),
#         bbox_transform=ax.transAxes,
#         borderpad=0
#     )

#     # Add colorbar
#     cbar1 = plt.colorbar(im, cax=cax, orientation="horizontal")

#     # Put ticks on top
#     cbar1.ax.xaxis.set_ticks_position("top")

#     # Format colorbar
#     cbar1.ax.tick_params(
#         labelsize=axis_num_fs,
#         which="major",
#         length=4,
#         direction="in",
#         width=spine_width
#     )

#     cbar1.outline.set_linewidth(spine_width)


#     # Add the vectors
#     for row in b['VectorsActual']:
#         ax.plot([row[0], row[1]], [row[2], row[3]], color='black', lw = vector_lw)

#     diff = 14
#     xmin = b['xmin'] + diff
#     xmax = b['xmax'] - diff
#     ymin = b['ymin'] + diff
#     ymax = b['ymax'] - diff



#     # Beam location
#     beam_x_pos = xmin - 0.1 * (xmin - xmax)
#     beam_y_pos = ymin - 0.1 * (ymin - ymax)


#     # Add y-axis label to the left
#     if i == 0:
#         ax.set_ylabel("Declination (ICRS)", fontsize=axis_label_fs)

#     # Add an x-axis label to all plots
#     ax.set_xlabel(" ")

#     # Set the x and y lims
#     ax.set_xlim(xmin, xmax)
#     ax.set_ylim(ymin, ymax)

#     # Add the line to each plot
#     # ---------------------------------------------------------
#     # Scalebar line
#     line_x_pos = xmax - 0.04 * (xmax - xmin)
#     line_y_pos = ymin - 0.14 * (ymin - ymax)  -10

#     x0 = line_x_pos - b['reference_length_pix']
#     x1 = line_x_pos

#     ax.plot(
#         [x0, x1],
#         [line_y_pos, line_y_pos],
#         color='black',
#         linewidth=AU100_lw
#     )

#     # ---------------------------------------------------------
#     # Convert midpoint from data coords -> axes coords
#     x_mid_data = (x0 + x1) / 2
#     y_mid_data = line_y_pos

#     display_coords = ax.transData.transform((x_mid_data, y_mid_data))
#     axes_coords = ax.transAxes.inverted().transform(display_coords)

#     x_axes, y_axes = axes_coords

#     # Text directly above middle of line
#     ax.text(
#         x_axes,
#         y_axes + 0.015,
#         f"{b['reference_length_AU']} AU",
#         transform=ax.transAxes,
#         fontsize=AU100_fs,
#         ha='center',
#         va='bottom'
#     )

#     add_band_label(ax, bands_idx[i], label, constants, x_pos = x_pos, y_pos = y_pos, 
#                    label_fs = text_fs, va = 'bottom')
#     # ---------------------------------------------------------


#     # Add the beam
#     beam = Ellipse((beam_x_pos, beam_y_pos), width=b['BMAJ_pix'], height=b['BMIN_pix'],  
#                angle=b['BPA_deg_cartesian'], edgecolor='black', facecolor='none', alpha=1, lw=beam_lw)

#     ax.add_patch(beam)

#     # Axis ticks and labels 
#     # ---------------------------------------------------------
#     # Only show y-axis numbers on far left plot
#     if i != 0:
#         ax.coords[1].set_ticklabel_visible(False)
#         ax.coords[1].set_axislabel('')
# #     # ---------------------------------------------------------
# #     # Tick locations and style
#     ax.coords[0].set_ticks(number=3, direction='in', width=spine_width)
#     ax.coords[1].set_ticks(number=5, direction='in', width=spine_width)

#     # Tick label sizes
#     ax.coords[0].set_ticklabel(size=axis_num_fs - 7)
#     ax.coords[1].set_ticklabel(size=axis_num_fs - 7)
# # #         # --------------------------------------------------------
#     # --------------------------------------------------------
# #     ax.coords[1].set_ticklabel_visible(True)
# #     ax.coords[0].set_ticklabel_visible(True)
#     # --------------------------------------------------------

# # Add streamer vectors to band 5 plot
# # for row in stream_vectors:
# #     axes[1].plot([row[0], row[1]], [row[2], row[3]], color='red', lw = vector_lw)



# fig.subplots_adjust(
#     left=0.05,
#     right=0.98,
#     bottom=0.12,
#     top=0.88,
#     wspace=0.12
# )


# fig.text(
#     0.5,          # centered
#     0.97,         # adjust as needed
#     r'Polarized Intensity [mJy beam$^{-1}$]',
#     ha='center',
#     va='top',
#     fontsize=cbar_label_fs
# )



# fig.text(
#     0.5,
#     0.1,
#     "Right Ascension (ICRS)",
#     ha='center',
#     fontsize=axis_label_fs
# )

    
    
# plt.savefig(image_folder_path + '/WRITEUP/StokesI_POLI/' + "POLI_grid_robust_minus1.pdf", 
#             dpi=500, 
#             bbox_inches='tight',
#                facecolor='white')


# plt.savefig(image_folder_path + '/SLIDESHOW/POLI/' + "POLI_grid_robust_minus1.jpeg", 
#             dpi=500, 
#             bbox_inches='tight',
#                facecolor='white')

# Minor axis slice grid

In [ ]:
# # def MakeAllBandGrid(B4, B5, B6, B7,
# #                    fig_x_size = 20, 
# #                     fig_y_size = 6.5,
# #                     label = 'wavelength',
# #                     cmap = soft_colormap_v2,
# #                    vector_lw = 2.2,
# #                    axis_num_fs = 16,
# #                 axis_label_fs = 22, 
# #                    scalebar_fs = 16,
# #                    beam_lw = 1.5,
# #                    cbar_label_fs = 20,
# #                     # This is for the 100 AU and label text
# #                     x_pos = 0.06, 
# #                     y_pos = 0.85,
# #                     AU100_lw = 2.5,
# #                     AU100_fs = 20, 
# #                     text_fs = 20, 
# #                     wspace = 0.12,
# #                    for_poster = False,
# #                    ps = 1,
# #                    cbar_shrink = 1):
    
# # Set initial things
# # ------------------------------
# fig_x_size = 14
# fig_y_size = 5
# # ------------------------------
# text_fs = 25
# spine_width = 1
# # ------------------------------
# cmap = soft_colormap_v2
# AU100_lw = 2.5
# AU100_fs = 20
# label = 'wavelength'
# x_pos = 0.06 
# y_pos = 0.85
# beam_lw = 1.5
# cbar_label_fs = 20
# # ------------------------------


# bands = [B4, B5, B6, B7]
# bands_idx = [4, 5, 6, 7]

# # These things should be the same for all bands
# StokesI_wcs = B4['StokesI_wcs']



# # Make the figure
# fig = plt.figure(figsize=(fig_x_size, fig_y_size))
# axes = []

# for i, b in enumerate(bands):


#     ax = fig.add_subplot(1, 4, i + 1, projection=b['StokesI_wcs'])
#     axes.append(ax)
    
#     # Add the slice



#     ax.coords.frame.set_linewidth(spine_width)


#     # Plot POLI
#     im = ax.imshow(b['POLI_debiased_mJy'], cmap = cmap)
    
#     # Add the slice
#     # ------------------------------------------------------------------------------
# #     ax.scatter(b['minor_x'],
# #                b['minor_y'],
# #                color="red",
# #                s=30,
# #                zorder=1000)
    
#     ax.plot(b['minor_x'],
#             b['minor_y'],
#             label = 'Minor Axis Slice',
#             color = 'grey',
#             lw = 3, 
#             ls = "--")
#     # ------------------------------------------------------------------------------

#     # Add a cbar

#     # Make colorbar axis above plot
#     cax = inset_axes(
#         ax,
#         width="100%",
#         height="6%",
#         loc="upper center",
#         bbox_to_anchor=(0, 0.075, 1, 1),
#         bbox_transform=ax.transAxes,
#         borderpad=0
#     )

#     # Add colorbar
#     cbar1 = plt.colorbar(im, cax=cax, orientation="horizontal")

#     # Put ticks on top
#     cbar1.ax.xaxis.set_ticks_position("top")

#     # Format colorbar
#     cbar1.ax.tick_params(
#         labelsize=axis_num_fs,
#         which="major",
#         length=4,
#         direction="in",
#         width=spine_width
#     )

#     cbar1.outline.set_linewidth(spine_width)


#     xmin = b['xmin']
#     xmax = b['xmax']
#     ymin = b['ymin']
#     ymax = b['ymax']

# #         print(f'Band = {i}, and ymax = {ymax}')


#     # Beam location
#     beam_x_pos = xmin - 0.1 * (xmin - xmax)
#     beam_y_pos = ymin - 0.1 * (ymin - ymax)


#     # Add y-axis label to the left
#     if i == 0:
#         ax.set_ylabel("Declination (ICRS)", fontsize=axis_label_fs)

#     # Add an x-axis label to all plots
#     ax.set_xlabel(" ")

#     # Set the x and y lims
#     ax.set_xlim(xmin, xmax)
#     ax.set_ylim(ymin, ymax)

#     # Add the line to each plot
#     # ---------------------------------------------------------
#     # Scalebar line
#     line_x_pos = xmax - 0.04 * (xmax - xmin)
#     line_y_pos = ymin - 0.14 * (ymin - ymax)  -10

#     x0 = line_x_pos - b['reference_length_pix']
#     x1 = line_x_pos

#     ax.plot(
#         [x0, x1],
#         [line_y_pos, line_y_pos],
#         color='black',
#         linewidth=AU100_lw
#     )

#     # ---------------------------------------------------------
#     # Convert midpoint from data coords -> axes coords
#     x_mid_data = (x0 + x1) / 2
#     y_mid_data = line_y_pos

#     display_coords = ax.transData.transform((x_mid_data, y_mid_data))
#     axes_coords = ax.transAxes.inverted().transform(display_coords)

#     x_axes, y_axes = axes_coords

#     # Text directly above middle of line
#     ax.text(
#         x_axes,
#         y_axes + 0.015,
#         f"{b['reference_length_AU']} AU",
#         transform=ax.transAxes,
#         fontsize=AU100_fs,
#         ha='center',
#         va='bottom'
#     )

#     add_band_label(ax, bands_idx[i], label, constants, x_pos = x_pos, y_pos = y_pos, 
#                    label_fs = text_fs, va = 'bottom')
#     # ---------------------------------------------------------


#     # Add the beam
#     beam = Ellipse((beam_x_pos, beam_y_pos), width=b['BMAJ_pix'], height=b['BMIN_pix'],  
#                angle=b['BPA_deg_cartesian'], edgecolor='black', facecolor='none', alpha=1, lw=beam_lw)

#     ax.add_patch(beam)

#     # Axis ticks and labels 
#     # ---------------------------------------------------------
#     # Only show y-axis numbers on far left plot
#     if i != 0:
#         ax.coords[1].set_ticklabel_visible(False)
#         ax.coords[1].set_axislabel('')
#     # ---------------------------------------------------------
#     # Tick locations and style
#     ax.coords[0].set_ticks(number=3, direction='in', width=spine_width)
#     ax.coords[1].set_ticks(number=5, direction='in', width=spine_width)

#     # Tick label sizes
#     ax.coords[0].set_ticklabel(size=axis_num_fs)
#     ax.coords[1].set_ticklabel(size=axis_num_fs)
# #         # --------------------------------------------------------





# fig.text(
#     0.5,
#     0.03,
#     "Right Ascension (ICRS)",
#     ha='center',
#     fontsize=axis_label_fs
# )


# fig.text(
#     0.5,          # centered
#     0.995,         # adjust as needed
#     r'Polarized Intensity [mJy beam$^{-1}$]',
#     ha='center',
#     va='top',
#     fontsize=cbar_label_fs
# )

    




# plt.savefig(image_folder_path + "WRITEUP/Slices/" + "MinorAxisSliceGrid.pdf", 
#             dpi=300, 
#             bbox_inches='tight')

In [ ]:
# # def MakeAllBandGrid(B4, B5, B6, B7,
# #                    fig_x_size = 20, 
# #                     fig_y_size = 6.5,
# #                     label = 'wavelength',
# #                     cmap = soft_colormap_v2,
# #                    vector_lw = 2.2,
# #                    axis_num_fs = 16,
# #                 axis_label_fs = 22, 
# #                    scalebar_fs = 16,
# #                    beam_lw = 1.5,
# #                    cbar_label_fs = 20,
# #                     # This is for the 100 AU and label text
# #                     x_pos = 0.06, 
# #                     y_pos = 0.85,
# #                     AU100_lw = 2.5,
# #                     AU100_fs = 20, 
# #                     text_fs = 20, 
# #                     wspace = 0.12,
# #                    for_poster = False,
# #                    ps = 1,
# #                    cbar_shrink = 1):
    
# # Set initial things
# # ------------------------------
# fig_x_size = 14
# fig_y_size = 5
# # ------------------------------
# text_fs = 25
# spine_width = 1
# # ------------------------------
# cmap = soft_colormap_v2
# AU100_lw = 2.5
# AU100_fs = 20
# label = 'wavelength'
# x_pos = 0.06 
# y_pos = 0.85
# beam_lw = 1.5
# cbar_label_fs = 20
# # ------------------------------


# bands = [B4, B5_R1, B6, B7]
# bands_idx = [4, 51, 6, 7]

# # These things should be the same for all bands
# StokesI_wcs = B4['StokesI_wcs']



# # Make the figure
# fig = plt.figure(figsize=(fig_x_size, fig_y_size))
# axes = []

# for i, b in enumerate(bands):


#     ax = fig.add_subplot(1, 4, i + 1, projection=b['StokesI_wcs'])
#     axes.append(ax)
    
#     # Add the slice



#     ax.coords.frame.set_linewidth(spine_width)


#     # Plot POLI
#     im = ax.imshow(b['POLI_debiased_mJy'], cmap = cmap)
    
#     # Add the slice
#     # ------------------------------------------------------------------------------
# #     ax.scatter(b['minor_x'],
# #                b['minor_y'],
# #                color="red",
# #                s=30,
# #                zorder=1000)
    
#     ax.plot(b['minor_x'],
#             b['minor_y'],
#             label = 'Minor Axis Slice',
#             color = 'grey',
#             lw = 3, 
#             ls = "--")
#     # ------------------------------------------------------------------------------

#     # Add a cbar

#     # Make colorbar axis above plot
#     cax = inset_axes(
#         ax,
#         width="100%",
#         height="6%",
#         loc="upper center",
#         bbox_to_anchor=(0, 0.075, 1, 1),
#         bbox_transform=ax.transAxes,
#         borderpad=0
#     )

#     # Add colorbar
#     cbar1 = plt.colorbar(im, cax=cax, orientation="horizontal")

#     # Put ticks on top
#     cbar1.ax.xaxis.set_ticks_position("top")

#     # Format colorbar
#     cbar1.ax.tick_params(
#         labelsize=axis_num_fs,
#         which="major",
#         length=4,
#         direction="in",
#         width=spine_width
#     )

#     cbar1.outline.set_linewidth(spine_width)


#     xmin = b['xmin']
#     xmax = b['xmax']
#     ymin = b['ymin']
#     ymax = b['ymax']

# #         print(f'Band = {i}, and ymax = {ymax}')


#     # Beam location
#     beam_x_pos = xmin - 0.1 * (xmin - xmax)
#     beam_y_pos = ymin - 0.1 * (ymin - ymax)


#     # Add y-axis label to the left
#     if i == 0:
#         ax.set_ylabel("Declination (ICRS)", fontsize=axis_label_fs)

#     # Add an x-axis label to all plots
#     ax.set_xlabel(" ")

#     # Set the x and y lims
#     ax.set_xlim(xmin, xmax)
#     ax.set_ylim(ymin, ymax)

#     # Add the line to each plot
#     # ---------------------------------------------------------
#     # Scalebar line
#     line_x_pos = xmax - 0.04 * (xmax - xmin)
#     line_y_pos = ymin - 0.14 * (ymin - ymax)  -10

#     x0 = line_x_pos - b['reference_length_pix']
#     x1 = line_x_pos

#     ax.plot(
#         [x0, x1],
#         [line_y_pos, line_y_pos],
#         color='black',
#         linewidth=AU100_lw
#     )

#     # ---------------------------------------------------------
#     # Convert midpoint from data coords -> axes coords
#     x_mid_data = (x0 + x1) / 2
#     y_mid_data = line_y_pos

#     display_coords = ax.transData.transform((x_mid_data, y_mid_data))
#     axes_coords = ax.transAxes.inverted().transform(display_coords)

#     x_axes, y_axes = axes_coords

#     # Text directly above middle of line
#     ax.text(
#         x_axes,
#         y_axes + 0.015,
#         f"{b['reference_length_AU']} AU",
#         transform=ax.transAxes,
#         fontsize=AU100_fs,
#         ha='center',
#         va='bottom'
#     )

#     add_band_label(ax, bands_idx[i], label, constants, x_pos = x_pos, y_pos = y_pos, 
#                    label_fs = text_fs, va = 'bottom')
#     # ---------------------------------------------------------


#     # Add the beam
#     beam = Ellipse((beam_x_pos, beam_y_pos), width=b['BMAJ_pix'], height=b['BMIN_pix'],  
#                angle=b['BPA_deg_cartesian'], edgecolor='black', facecolor='none', alpha=1, lw=beam_lw)

#     ax.add_patch(beam)

#     # Axis ticks and labels 
#     # ---------------------------------------------------------
#     # Only show y-axis numbers on far left plot
#     if i != 0:
#         ax.coords[1].set_ticklabel_visible(False)
#         ax.coords[1].set_axislabel('')
#     # ---------------------------------------------------------
#     # Tick locations and style
#     ax.coords[0].set_ticks(number=3, direction='in', width=spine_width)
#     ax.coords[1].set_ticks(number=5, direction='in', width=spine_width)

#     # Tick label sizes
#     ax.coords[0].set_ticklabel(size=axis_num_fs)
#     ax.coords[1].set_ticklabel(size=axis_num_fs)
# #         # --------------------------------------------------------




# fig.subplots_adjust(
#     left=0.05,
#     right=0.98,
#     bottom=0.12,
#     top=0.88,
#     wspace=0.12
# )


# fig.text(
#     0.5,          # centered
#     0.99,         # adjust as needed
#     r'Polarized Intensity [mJy beam$^{-1}$]',
#     ha='center',
#     va='top',
#     fontsize=cbar_label_fs
# )



# fig.text(
#     0.5,
#     0.05,
#     "Right Ascension (ICRS)",
#     ha='center',
#     fontsize=axis_label_fs
# )

    




# plt.savefig(image_folder_path + "WRITEUP/Slices/" + "MinorAxisSliceGrid_robust_minus1.pdf", 
#             dpi=300, 
#             bbox_inches='tight')